//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickSort.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickSort.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Browse... ähnelt.
        /// </summary>
        public static string btnConfig_Browse {
            get {
                return ResourceManager.GetString("btnConfig_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save settings ähnelt.
        /// </summary>
        public static string btnConfig_SaveConfig {
            get {
                return ResourceManager.GetString("btnConfig_SaveConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancle ähnelt.
        /// </summary>
        public static string btnFileMoveDlg_Cancle {
            get {
                return ResourceManager.GetString("btnFileMoveDlg_Cancle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move ähnelt.
        /// </summary>
        public static string btnFileMoveDlg_StartMove {
            get {
                return ResourceManager.GetString("btnFileMoveDlg_StartMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Accept ähnelt.
        /// </summary>
        public static string btnNewFolderDlg_Accept {
            get {
                return ResourceManager.GetString("btnNewFolderDlg_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancle ähnelt.
        /// </summary>
        public static string btnNewFolderDlg_Cancle {
            get {
                return ResourceManager.GetString("btnNewFolderDlg_Cancle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add entry ähnelt.
        /// </summary>
        public static string cmFavTargFolder_AddEntry {
            get {
                return ResourceManager.GetString("cmFavTargFolder_AddEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add entry ähnelt.
        /// </summary>
        public static string cmFavTargFolder_AddEntry2 {
            get {
                return ResourceManager.GetString("cmFavTargFolder_AddEntry2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move images here ähnelt.
        /// </summary>
        public static string cmFavTargFolder_MoveImageHere {
            get {
                return ResourceManager.GetString("cmFavTargFolder_MoveImageHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove bookmark ähnelt.
        /// </summary>
        public static string cmFavTargFolder_RemoveBookmark {
            get {
                return ResourceManager.GetString("cmFavTargFolder_RemoveBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove entry ähnelt.
        /// </summary>
        public static string cmFavTargFolder_RemoveEntry {
            get {
                return ResourceManager.GetString("cmFavTargFolder_RemoveEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set bookmark ähnelt.
        /// </summary>
        public static string cmFavTargFolder_SetBookmark {
            get {
                return ResourceManager.GetString("cmFavTargFolder_SetBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Large icon size ähnelt.
        /// </summary>
        public static string cmFileTitleSec_ButtonLargeIconSize {
            get {
                return ResourceManager.GetString("cmFileTitleSec_ButtonLargeIconSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Medium icon size ähnelt.
        /// </summary>
        public static string cmFileTitleSec_ButtonMediumIconSize {
            get {
                return ResourceManager.GetString("cmFileTitleSec_ButtonMediumIconSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Small icon size ähnelt.
        /// </summary>
        public static string cmFileTitleSec_ButtonSmalIconSize {
            get {
                return ResourceManager.GetString("cmFileTitleSec_ButtonSmalIconSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deselect all ähnelt.
        /// </summary>
        public static string cmFileTitleSec_DeSelectAll {
            get {
                return ResourceManager.GetString("cmFileTitleSec_DeSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refresh folder ähnelt.
        /// </summary>
        public static string cmFileTitleSec_RefreshView {
            get {
                return ResourceManager.GetString("cmFileTitleSec_RefreshView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select all ähnelt.
        /// </summary>
        public static string cmFileTitleSec_SelectAll {
            get {
                return ResourceManager.GetString("cmFileTitleSec_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add entry ähnelt.
        /// </summary>
        public static string cmVirtualDirSec_AddEntry {
            get {
                return ResourceManager.GetString("cmVirtualDirSec_AddEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add entry ähnelt.
        /// </summary>
        public static string cmVirtualDirSec_AddEntry2 {
            get {
                return ResourceManager.GetString("cmVirtualDirSec_AddEntry2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create new folder ähnelt.
        /// </summary>
        public static string cmVirtualDirSec_CreateFolder {
            get {
                return ResourceManager.GetString("cmVirtualDirSec_CreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create new folder ähnelt.
        /// </summary>
        public static string cmVirtualDirSec_CreateFolder2 {
            get {
                return ResourceManager.GetString("cmVirtualDirSec_CreateFolder2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create new subfolder ähnelt.
        /// </summary>
        public static string cmVirtualDirSec_CreateSubFolder {
            get {
                return ResourceManager.GetString("cmVirtualDirSec_CreateSubFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete folder ähnelt.
        /// </summary>
        public static string cmVirtualDirSec_DeleteFolder {
            get {
                return ResourceManager.GetString("cmVirtualDirSec_DeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move images here ähnelt.
        /// </summary>
        public static string cmVirtualDirSec_MoveImageHere {
            get {
                return ResourceManager.GetString("cmVirtualDirSec_MoveImageHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open folder ähnelt.
        /// </summary>
        public static string cmVirtualDirSec_OpenFolder {
            get {
                return ResourceManager.GetString("cmVirtualDirSec_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove entry ähnelt.
        /// </summary>
        public static string cmVirtualDirSec_RemoveEntry {
            get {
                return ResourceManager.GetString("cmVirtualDirSec_RemoveEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A folder with the name \&quot;{0}\&quot; already exists. ähnelt.
        /// </summary>
        public static string dlg_ADirWithTheNewNameExists {
            get {
                return ResourceManager.GetString("dlg_ADirWithTheNewNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Files are currently being processed in the background.\n\nIf you close the application, this process will be aborted. Not all selected files will be moved to the destination folder!\n\nAre you sure you want to close the application? ähnelt.
        /// </summary>
        public static string dlg_AppExitFileCopyStillActive {
            get {
                return ResourceManager.GetString("dlg_AppExitFileCopyStillActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The selected directory:\n\n\t\&quot;{0}\&quot;\n\is not empty!\n\nAre your sure to delete the directory? ähnelt.
        /// </summary>
        public static string dlg_DelayNotEmptyDir {
            get {
                return ResourceManager.GetString("dlg_DelayNotEmptyDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not all images could be opened and displayed!\n\n[0] ähnelt.
        /// </summary>
        public static string dlg_ErrorLoadingImagesFromDir {
            get {
                return ResourceManager.GetString("dlg_ErrorLoadingImagesFromDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your configuration is invalid or has not been setup yet.\nFor this program to work properly, the folders must be configured correctly.\n\nShould the configuration window be displayed so that the settings can be adjusted? ähnelt.
        /// </summary>
        public static string dlg_InvalidConfig {
            get {
                return ResourceManager.GetString("dlg_InvalidConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The folder name \&quot;{0}\&quot; is not valid. ähnelt.
        /// </summary>
        public static string dlg_InvalidNewDirName {
            get {
                return ResourceManager.GetString("dlg_InvalidNewDirName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select default folder ähnelt.
        /// </summary>
        public static string dlgConfig_StartPath {
            get {
                return ResourceManager.GetString("dlgConfig_StartPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select new Favorites folder ähnelt.
        /// </summary>
        public static string dlgFavTargFolder_HelpText {
            get {
                return ResourceManager.GetString("dlgFavTargFolder_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select folder to add ähnelt.
        /// </summary>
        public static string dlgVirtualDirSec_HelpText {
            get {
                return ResourceManager.GetString("dlgVirtualDirSec_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Folder already exists. ähnelt.
        /// </summary>
        public static string lDirectoyExists {
            get {
                return ResourceManager.GetString("lDirectoyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Folder does not exists. ähnelt.
        /// </summary>
        public static string lDirectoyNotExists {
            get {
                return ResourceManager.GetString("lDirectoyNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string lError {
            get {
                return ResourceManager.GetString("lError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid folder name. ähnelt.
        /// </summary>
        public static string lInvalidDirName {
            get {
                return ResourceManager.GetString("lInvalidDirName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New folder name ähnelt.
        /// </summary>
        public static string lNewFolder {
            get {
                return ResourceManager.GetString("lNewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Input field is empty ähnelt.
        /// </summary>
        public static string lNoText {
            get {
                return ResourceManager.GetString("lNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number must between {0} and {1}. ähnelt.
        /// </summary>
        public static string lNumberRangeError {
            get {
                return ResourceManager.GetString("lNumberRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text must be a number. ähnelt.
        /// </summary>
        public static string lTextMustBeANumber {
            get {
                return ResourceManager.GetString("lTextMustBeANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning ähnelt.
        /// </summary>
        public static string lWarning {
            get {
                return ResourceManager.GetString("lWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatically add entries to the favorites list ähnelt.
        /// </summary>
        public static string tbConfig_AutoInsertFavoriteTargetFolderCollectionItems {
            get {
                return ResourceManager.GetString("tbConfig_AutoInsertFavoriteTargetFolderCollectionItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximum entries in the favorites list ähnelt.
        /// </summary>
        public static string tbConfig_MaxFavoriteTargetFolderCollectionItems {
            get {
                return ResourceManager.GetString("tbConfig_MaxFavoriteTargetFolderCollectionItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show filenames of images ähnelt.
        /// </summary>
        public static string tbConfig_ShowImgFileName {
            get {
                return ResourceManager.GetString("tbConfig_ShowImgFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show security prompt before moving images ähnelt.
        /// </summary>
        public static string tbConfig_ShowMoveDlg {
            get {
                return ResourceManager.GetString("tbConfig_ShowMoveDlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default folder ähnelt.
        /// </summary>
        public static string tbConfig_StartPath {
            get {
                return ResourceManager.GetString("tbConfig_StartPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General folder settings ähnelt.
        /// </summary>
        public static string tbConfig_Title1 {
            get {
                return ResourceManager.GetString("tbConfig_Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Other settings ähnelt.
        /// </summary>
        public static string tbConfig_Title2 {
            get {
                return ResourceManager.GetString("tbConfig_Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use Dark Mode theme ähnelt.
        /// </summary>
        public static string tbConfig_UseDarkModeColorTheme {
            get {
                return ResourceManager.GetString("tbConfig_UseDarkModeColorTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die iCloudHelper - Settings ähnelt.
        /// </summary>
        public static string tbConfig_WindowTitle {
            get {
                return ResourceManager.GetString("tbConfig_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Right-click to add new favorites ähnelt.
        /// </summary>
        public static string tbFavTargFolder_NoItemText {
            get {
                return ResourceManager.GetString("tbFavTargFolder_NoItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Favorites ähnelt.
        /// </summary>
        public static string tbFavTargFolder_Title {
            get {
                return ResourceManager.GetString("tbFavTargFolder_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Should the {0} selected images be moved to &quot;{1}&quot;? ähnelt.
        /// </summary>
        public static string tbFileMoveDlg_QuestionText {
            get {
                return ResourceManager.GetString("tbFileMoveDlg_QuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Question ähnelt.
        /// </summary>
        public static string tbFileMoveDlg_QuestionTitle {
            get {
                return ResourceManager.GetString("tbFileMoveDlg_QuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Image:  ähnelt.
        /// </summary>
        public static string tbFileMovePopup_FileLabel {
            get {
                return ResourceManager.GetString("tbFileMovePopup_FileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Target folder:  ähnelt.
        /// </summary>
        public static string tbFileMovePopup_TargetPathLabel {
            get {
                return ResourceManager.GetString("tbFileMovePopup_TargetPathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading images... ([0]/[1]) ähnelt.
        /// </summary>
        public static string tbFileTitleSec_LodingImages {
            get {
                return ResourceManager.GetString("tbFileTitleSec_LodingImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No images found. Use the settings to change the source folder. ähnelt.
        /// </summary>
        public static string tbFileTitleSec_NoItemText {
            get {
                return ResourceManager.GetString("tbFileTitleSec_NoItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1 image selected ähnelt.
        /// </summary>
        public static string tbFileTitleSec_SubTitle_1 {
            get {
                return ResourceManager.GetString("tbFileTitleSec_SubTitle_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [0] images selected ähnelt.
        /// </summary>
        public static string tbFileTitleSec_SubTitle_2 {
            get {
                return ResourceManager.GetString("tbFileTitleSec_SubTitle_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Image selection ähnelt.
        /// </summary>
        public static string tbFileTitleSec_Title {
            get {
                return ResourceManager.GetString("tbFileTitleSec_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New folder name: ähnelt.
        /// </summary>
        public static string tbNewFolderDlg_QuestionText {
            get {
                return ResourceManager.GetString("tbNewFolderDlg_QuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Question ähnelt.
        /// </summary>
        public static string tbNewFolderDlg_QuestionTitle {
            get {
                return ResourceManager.GetString("tbNewFolderDlg_QuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Right-click to add folders ähnelt.
        /// </summary>
        public static string tbVirtualDirSec_NoItemText {
            get {
                return ResourceManager.GetString("tbVirtualDirSec_NoItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Target folder ähnelt.
        /// </summary>
        public static string tbVirtualDirSec_Title {
            get {
                return ResourceManager.GetString("tbVirtualDirSec_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name:    \t[0]\nFolder:  \t[1] ähnelt.
        /// </summary>
        public static string ttFavTargFolder_FavTargetItem {
            get {
                return ResourceManager.GetString("ttFavTargFolder_FavTargetItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deselect all ähnelt.
        /// </summary>
        public static string ttFileTitleSec_ButtonDeselectAll {
            get {
                return ResourceManager.GetString("ttFileTitleSec_ButtonDeselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Large icon size ähnelt.
        /// </summary>
        public static string ttFileTitleSec_ButtonLargeIconSize {
            get {
                return ResourceManager.GetString("ttFileTitleSec_ButtonLargeIconSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Medium icon size ähnelt.
        /// </summary>
        public static string ttFileTitleSec_ButtonMediumIconSize {
            get {
                return ResourceManager.GetString("ttFileTitleSec_ButtonMediumIconSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select all ähnelt.
        /// </summary>
        public static string ttFileTitleSec_ButtonSelectAll {
            get {
                return ResourceManager.GetString("ttFileTitleSec_ButtonSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string ttFileTitleSec_Buttonsettings {
            get {
                return ResourceManager.GetString("ttFileTitleSec_Buttonsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Small icon size ähnelt.
        /// </summary>
        public static string ttFileTitleSec_ButtonSmalIconSize {
            get {
                return ResourceManager.GetString("ttFileTitleSec_ButtonSmalIconSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name:            \t[0]\nFolder:          \t[1]\nSize:            \t[2]kB\nCreation date:   \t[3]\nLast access:     \t[4] ähnelt.
        /// </summary>
        public static string ttFileTitleSec_FileTitleItem {
            get {
                return ResourceManager.GetString("ttFileTitleSec_FileTitleItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name:            \t[0]\nFolder:          \t[1]\nFile count:      \t[2]\nSubfilder count: \t[3] ähnelt.
        /// </summary>
        public static string ttVirtualDirSec_DirItem {
            get {
                return ResourceManager.GetString("ttVirtualDirSec_DirItem", resourceCulture);
            }
        }
    }
}
